#!/usr/bin/env python

import rospy
import json
from std_msgs.msg import String, Bool
from geometry_msgs.msg import Point

import sys
import os
import time
# import airsim

# 获取当前脚本的目录
current_dir = os.path.dirname(os.path.abspath(__file__))
# 构建从当前目录到airsim库目录的相对路径
relative_path = os.path.join(current_dir, '..', '..', '..', '..', 'PythonClient')
# 将相对路径添加到sys.path中
sys.path.append(relative_path)
# 现在你可以导入airsim模块了
import airsim
from airsim import types

class UEROSBridge:
    def __init__(self, host_ip, vehicle_name):
        self.vehicle_name = vehicle_name
        
        state_pub_topic = "airsim_node/" + vehicle_name + "/vehicle_state"
        state_pub = rospy.Publisher(state_pub_topic, Bool, queue_size=10)

        isCollided_pub_topic = "/airsim_node/" + vehicle_name + "/is_collided"
        isCollided_pub = rospy.Publisher(isCollided_pub_topic, Bool, queue_size=10)

        collisionInfo_pub_topic =  "/airsim_node/" + vehicle_name + "/collide_point"
        collisionInfo_pub = rospy.Publisher(collisionInfo_pub_topic, Point, queue_size=10)

        
        # 初始化AirSim客户端
        global client
        client = airsim.CarClient(ip=host_ip)
        client.confirmConnection()

        # 注册关闭回调函数
        rospy.on_shutdown(self.shutdown_callback)

        rate = rospy.Rate(30)

        while not rospy.is_shutdown():
            isAlive = client.getVehicleState(vehicle_name)
            
            state_pub.publish(isAlive.state)

            collisionInfo = client.simGetCollisionInfo(vehicle_name)
            
            isCollided_pub.publish(collisionInfo.has_collided)

            # collisionInfo_pub.publish(String(json.dumps(collisionInfo)))
            
            collisionInfo_pub.publish(Point(collisionInfo.position.x_val,collisionInfo.position.y_val,collisionInfo.position.z_val))

            rate.sleep()

    def shutdown_callback(self):
        # 在这里添加任何需要在程序关闭时执行的清理操作
        print("Shutting down...")
        # 例如，关闭AirSim客户端连接
        # client.reset()

if __name__ == '__main__':
    rospy.init_node('ue_to_ros_bridge')

    # host_ip="127.0.0.1"
    host_ip = rospy.get_param('~host_ip', 'localhost')
    
    vehicle_name = rospy.get_param('~vehicle_name', 'drone_1')

    # 创建UEROSBridge实例
    bridge = UEROSBridge(host_ip, vehicle_name)

    rospy.spin()