#!/usr/bin/env python

import rospy
from nav_msgs.msg import Odometry

import sys
import os
import time
# import airsim

# 获取当前脚本的目录
current_dir = os.path.dirname(os.path.abspath(__file__))
# 构建从当前目录到airsim库目录的相对路径
relative_path = os.path.join(current_dir, '..', '..', '..', '..', 'PythonClient')
# 将相对路径添加到sys.path中
sys.path.append(relative_path)
# 现在你可以导入airsim模块了
import airsim

class UEROSBridge:
    def __init__(self, host_ip, vehicle_name):
        self.vehicle_name = vehicle_name
        
        # 初始化AirSim客户端
        global client
        client = airsim.CarClient(ip=host_ip)
        client.confirmConnection()

        # 注册关闭回调函数
        rospy.on_shutdown(self.shutdown_callback)

        while not rospy.is_shutdown():
            isAlive = client.getVehicleState(vehicle_name)
            # print(isAlive)
            time.sleep(0.01)
            enemys = client.getEnemyData()
            print(enemys)

    def shutdown_callback(self):
        # 在这里添加任何需要在程序关闭时执行的清理操作
        print("Shutting down...")
        # 例如，关闭AirSim客户端连接
        # client.reset()

if __name__ == '__main__':
    rospy.init_node('ue_to_ros_bridge')

    # host_ip="127.0.0.1"
    host_ip = rospy.get_param('~host_ip', 'localhost')
    
    vehicle_name = rospy.get_param('~vehicle_name', 'drone_1')

    # 创建UEROSBridge实例
    bridge = UEROSBridge(host_ip, vehicle_name)

    rospy.spin()